name: Fetch Football Matches

on:
  schedule:
    - cron: "0 */3 * * *"   # Every 3 hours
  workflow_dispatch:         # Allow manual trigger

jobs:
  fetch-matches:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install requests
        run: pip install requests

      # 4️⃣ Run Python script
      - name: Run matches.py
        env:
          API_KEY: ${{ secrets.API_SPORTS_KEY }}
        run: python matches.py

      # 5️⃣ Commit & Push updated JSON files
      - name: Commit & Push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add matches/*.json
          git commit -m "Update matches for $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push
