name: Shahid-Koora Scraper

on:
  workflow_dispatch:  # run manually
  schedule:
    - cron: "0 * * * *"   # every 1 hour

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer
              
      - name: Run scraper
        run: node scraper.js
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase origin main
          git add dataurls.json debug.html
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push origin main
