name: Update Shorts JSON

on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 */3 * * *"  # every 3 hours
  workflow_dispatch:        # allow manual run


jobs:
  update-shorts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add shorts_data/shorts.json
          git commit -m "Auto-update shorts.json" || echo "No changes to commit"
          git push
