name: Fetch Videos Data

on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 */3 * * *"  # every 3 hours
  workflow_dispatch: # allows manual trigger

jobs:
  fetch-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run video.py
        run: python video.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add videos_data/videos.json
          git commit -m "Auto-update videos.json" || echo "No changes to commit"
          git push
